### ISSUE TITLE
Update dropbox trained models with new configuration standard

### ISSUE THREAD

**Issue by dbellavista** [luca-m/emotime#40]
New emotime version requires `[TRAINING]` and `[VALIDATION]` configuration sections. The dropbox configuration needs to be updated.

**Comment by dbellavista** [comment]
See #39

**Comment by flecheria** [comment]
ok so is a dropbox files problem... ok.

**Comment by luca-m** [comment]
Training models in release [1.1](https://github.com/luca-m/emotime/releases/tag/v1.1-experimental) works with the source code of that release.

If you need some other models working in newer version check [v.1.2](https://github.com/luca-m/emotime/releases/tag/v1.2-experimental) release page, all needed info should be there.
