### ISSUE TITLE
ERR: something wrong ('module' object has no attribute 'next')

### ISSUE THREAD

**Issue by flecheria** [luca-m/emotime#42]
Fill dataset:  I'm not sure that I'm giving the right path, but it seems works... expect the error.
Thanks

c:\workspace\emotime\assets>python datasetFillCK.py --cfg test_dataset.cfg dataset_folder C:\workspace\emotime_dataset\ck\ck_plus\cohn-kanade-images C:\workspace\emotime_dataset\ck\ck_plus\Emotion
INFO: 123 subjects found in CK+ database
INFO: Processing subject S005
INFO: Processing shot 001
INFO: Picture 'S005_001_00000011.png' has been marked as disgust
ERR: something wrong ('module' object has no attribute 'next')

**Comment by dbellavista** [comment]
I cannot test it, but `next()` was used instead of `random()`.

**Comment by flecheria** [comment]
that's correct, now it works. I'm training
