### ISSUE TITLE
train_cli problem with openCV

### ISSUE THREAD

**Issue by flecheria** [luca-m/emotime#44]
I ran a brief test yesterday but I still have problem with this issue.
```
[FOLDER]
...
# Folder containing the csv files of the features for training set and validation set (one file per classifier)
TRAIN:      trainfiles
...
```
I miss the point. "trainfiles" is another folder where to put the csv. data?
Do we create this one with datasetInit.py? because right now "trainfiles" doesn't exist...
What does it change the name of the folder?

Last thing, in my previous test I failed one test with facecropping on neutral, is it possible that this result have some bad influence on the rest?

Thanks

**Comment by dbellavista** [comment]
Yes sorry the directory needs to be create by hand or by launching the
script.
If I recall correctly once face of fails to be recognized. BTW the major
influences other than the preprocessing are the svn  parameter and the
har-cascate face detector used.

**Comment by flecheria** [comment]
Ok, perfect. But what change if .csv are inside a folder named "trainfiles" or "training"? (that is where they are placed right now)

**Comment by luca-m** [comment]
```
.dataset
  \- classifiers // svm classifiers
  \- trainfiles // csv containing bad and good examples
  \- training // face and features here
  \- validation // other faces
```
