### ISSUE TITLE
libopencv_objdetect.so.2.4

### ISSUE THREAD

**Issue by shadkhan111** [luca-m/emotime#49]
what is the meaning of this error

**Comment by dbellavista** [comment]
Can you please report the exact command and the exact output. By the way this is most likely a bad installation of the opencv libraries (required >=2.4.5).

**Comment by shadkhan111** [comment]
command - ./emotimegui_cli ../resources//haarcascade_frontalface_cbcl1.xml none 48 3 5 4 svm ../dataset_svm_354_cbcl1_1vsallext/classifiers/svm/*

output - ./emotimegui_cli: error while loading shared libraries: libopencv_objdetect.so.2.4: cannot open shared object file: No such file or directory

**Comment by dbellavista** [comment]
You haven't installed or configured the correct opencv libraries. (http://opencv.org/)
