### ISSUE TITLE
VIDIOC_QUERYMENU: Invalid argument

### ISSUE THREAD

**Issue by rambir1** [luca-m/emotime#50]
when i m running this command ...
following messages shows up....
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument

and sometime this work quiet slow...

and you had give the link of version 1.2  in that  1vsall and 1vsallext link are  not working....

**Comment by luca-m** [comment]
the link of models in release 1.2 are working from my pc .. 
Could you be more precise with the command you are running?

**Comment by luca-m** [comment]
ref #51
