### ISSUE TITLE
VIDIOC_QUERYMENU: Invalid argument

### ISSUE THREAD

**Issue by sunshinecool** [luca-m/emotime#51]
![screenshot from 2015-06-12 12 19 09](https://cloud.githubusercontent.com/assets/6102696/8124843/50e77260-10fd-11e5-8386-a4e31d8d6354.png)
When I try to run the command
````
./emotimegui_cli ../resources/haarcascade_frontalface_cbcl1.xml ../resources/haarcascade_eye.xml 52 52 1 5 8 svm ../svm_1vsall_1_5_8_95c2eb0b58/*
````
this errors comes up. I have downloaded the trained models from https://github.com/luca-m/emotime/releases

**Comment by budasuyasa** [comment]
I got same error here.

**Comment by budasuyasa** [comment]
The process is prety slow. After wait for a while i got this.
![screenshot from 2015-09-02 10 54 32](https://cloud.githubusercontent.com/assets/5938250/9622088/65881a54-5161-11e5-88fd-670595eb169e.png)

**Comment by luca-m** [comment]
screen is not updated if no face is detected. Illumination may play a role. However i'll check.
