### ISSUE TITLE
Error CMAKE

### ISSUE THREAD

**Issue by budasuyasa** [luca-m/emotime#52]
I have installed opencv 3.0 and opencv-contrib but when i try to cmake, i got the following errors

CMake Error at /usr/local/share/OpenCV/OpenCVConfig.cmake:217 (message):
  opencv_contrib is required but was not found
Call Stack (most recent call first):
  src/training/CMakeLists.txt:9 (FIND_PACKAGE)

Did i miss something?

**Comment by luca-m** [comment]
with opencv opencv-2.4.9 works good, i'll give a try with 3.0

**Comment by budasuyasa** [comment]
Oke i will wait for it

**Comment by luca-m** [comment]
I'm experiencing some problems in compiling opencv 3.0 ..

**Comment by budasuyasa** [comment]
Thanks lucam. I will try with Opencv 2.4.9 then.
