### ISSUE TITLE
purpose of the commnd python gui.py 

### ISSUE THREAD

**Issue by r-sreesaran** [luca-m/emotime#57]
python gui.py --cfg <dataset_configuration_path> --mode svm --eye-correction <dataset_path> 

will running the command give my photos emotions ? 

when i ran the command i got the following error 
Launching emotime gui! Smile :)
OpenCV Error: Parsing error (../datasets/classifiers/svm/S032_002_01351504.png(1): Valid XML should start with '<?xml ...?>') in icvXMLParse, file /root/essentials/opencv/opencv-2.4.9/modules/core/src/persistence.cpp, line 2252
terminate called after throwing an instance of 'cv::Exception'
  what():  /root/essentials/opencv/opencv-2.4.9/modules/core/src/persistence.cpp:2252: error: (-212) ../datasets/classifiers/svm/S032_002_01351504.png(1): Valid XML should start with '<?xml ...?>' in function icvXMLParse

**Comment by luca-m** [comment]
That command is a wrapper for the webcam chi, you can invoke it directly
from the binary utilities. There are also utility to run it with video and
pics.. check the asset dir.
Il 21/nov/2015 20:21, "SreeSaran" <notifications@github.com> ha scritto:
