### ISSUE TITLE
'CvBoost' has not been declared problem

### ISSUE THREAD

**Issue by KyungwhaPark** [luca-m/emotime#60]
I'm running this in linux server, openCV 3.1 version.

as i read previous forum thread, it seems like opencv version problem.

following is the log.

[  1%] Building CXX object src/CMakeFiles/emotime.dir/detector/EmoDetector.cpp.o
In file included from /home/kwpark/code/emotime/src/training/Classifier.h:11:0,
                 from /home/kwpark/code/emotime/src/detector/EmoDetector.h:22,
                 from /home/kwpark/code/emotime/src/detector/EmoDetector.cpp:22:
/home/kwpark/code/emotime/src/training/TrainingParameters.h:25:26: error: ‘CvBoost’ has not been declared
make[2]: *** [src/CMakeFiles/emotime.dir/detector/EmoDetector.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/emotime.dir/all] Error 2
make: *** [all] Error 2

do i have to downgrade my opencv?

**Comment by ritou11** [comment]
Emotime uses Opencv 2. It can't find CvBoost in Opencv 3.

**Comment by luca-m** [comment]
not yet ported to OpenCV3, I'll take note of that. Thanks for opening the issue.
