### ISSUE TITLE
Information about Training

### ISSUE THREAD

**Issue by mastiffs92** [luca-m/emotime#61]
Hi,
in the training section of your library,
 what do you mean for CONFIGFILE and EMPTY_DATASET_FOLDER?

**Comment by dbellavista** [comment]
Could you please correct the question?

**Comment by mastiffs92** [comment]
Hi,
in the training section of your library,
what do you mean for CONFIGFILE and EMPTY_DATASET_FOLDER?

**Comment by mastiffs92** [comment]
I have this problem:
![screen_emotime](https://cloud.githubusercontent.com/assets/15649307/12309321/46b59c1c-ba4a-11e5-81c3-50da13766f53.png)

**Comment by mastiffs92** [comment]
pth=join(dsPath, config['CLASSIFIER_SVM_FOLDER'])
    if not os.path.exists(pth):
      os.makedirs(pth)
 -  pth=join(dsPath, config['CLAADAFIER_ADA_FOLDER'])
 +  pth=join(dsPath, config['CLASSIFIER_ADA_FOLDER'])
    if not os.path.exists(pth):
      os.makedirs(pth)
    # Copy configuration

**Comment by mastiffs92** [comment]
Resolved.
