### ISSUE TITLE
running emo_detector_cli

### ISSUE THREAD

**Issue by r-sreesaran** [luca-m/emotime#68]
On running the command with these parameter the following error throws up , please clarify what is given wrongly 
Note: this was done using experimental "R.C 1.1" from the following location https://github.com/luca-m/emotime/releases/tag/v1.1-experimental

./emo_detector_cli svm ../resources/haarcascade_frontalface_default.xml ../resources/haarcascade_eye.xml 52 52 1 5 8 ../compiled/dataset_svm_354_cbcl1_1vsall/classifiers/*
Insert the image file path: 
/root/github/emotime/datasets/classifiers/svm/S032_002_01351426.png

OpenCV Error: Bad argument (The SVM should be trained first) in CvSVM::predict, file /root/essentials/opencv/opencv-2.4.9/modules/ml/src/svm.cpp, line 2131
terminate called after throwing an instance of 'cv::Exception'
what(): /root/essentials/opencv/opencv-2.4.9/modules/ml/src/svm.cpp:2131: error: (-5) The SVM should be trained first in function CvSVM::predict

**Comment by mastiffs92** [comment]
you try to use this version.
https://github.com/luca-m/emotime/archive/master.zip

**Comment by egottardo** [comment]
It's seems that isn't finding trainned model (.xml files) in '../compiled/dataset_svm_354_cbcl1_1vsall/classifiers/*'.
Could you list the content of this directory?

**Comment by luca-m** [comment]
no answer from the issuer, closing
