### ISSUE TITLE
Starting Emotime

### ISSUE THREAD

**Issue by jpraciles** [luca-m/emotime#69]
Sorry for this question but i am just a newbie on this field. how to start emotime. pls answer....thank you

**Comment by husnain-ahmad** [comment]
Make sure that all the per-requisites are fulfilled like OpenCV and cmake etc.
First of all compile the package you have downloaded. If it is a .zip then unzip it and use navigate to build directory inside it using command line. In case of a .tar.gz file, untar it using tar -xf <file> from command line or using GUI archive manager.
Compiling steps are described on the main page of emotime pacakge.
After compilation navigate to assets directory inside emotime. There will be some executables, py scripts and some cfg files among others. If you can see this kind of stuff in assets folder then you are good to proceed to the next step.
Download the trained svm classifers from the given link. If you are using the master version of emotime, try the classifiers available at [https://copy.com/c4rOYmPgAYrdxdoS/svm_1vsallext_74_74_1_5_8_7bfc0cda.tar.gz?download=1](url)
Untar the downloaded file inside the emotime folder and use the following command to start emotime gui from within the assets folder.
`./emotimegui_cli ../resources/haarcascade_frontalface_cbcl1.xml none 48 48 3 5 4 svm ..<give the path of the downloaded classifiers in the last step here>/*.xml`

**Comment by cikel87** [comment]
Hi, somebody know whats mean this error on windows cmd:

"ERR: something wrong ([Errno 2] No such file or directory: './facecrop_cli.cpp.e
xe')"

This error show when i input datasetInit.py --cfg .....

Thanks

**Comment by abhaymir** [comment]
I used experimental releases and source code also. But the error is same

I tried like this 
```
./emotimegui_cli ../resources/haarcascade_frontalface_cbcl1.xml ../resources/haarcascade_eye.xml 52 52 1 5 8 svm ../svm_1vsall_1_5_8_95c2eb0b58/*
./emotimegui_cli ../resources/haarcascade_frontalface_cbcl1.xml ../resources/haarcascade_eye.xml 52 52 1 5 8 svm ../svm_1vsallext_1_5_8_95c2eb0b58/*
```
emotimegui loaded and closed quickly
command line output is

> init done
> opengl support available
> Segmentation fault (core dumped)

I tried this way too
```
./emo_detector_cli svm ../resources/haarcascade_frontalface_default.xml ../resources/haarcascade_eye.xml 53 53 1 5 8 ../../svm_1vsallext_1_5_8_95c2eb0b58/*.xml
Insert the image file path: 
/home/turbo/emotime-master/S045_001_00000001.png
```
command line output is
> 
> Processing '/home/turbo/emotime-master/S045_001_00000001.png'
> OpenCV Error: Bad argument (The SVM should be trained first) in CvSVM::predict, file /home/turbo/opencv-2.4.9/modules/ml/src/svm.cpp, line 2131
> terminate called after throwing an instance of 'cv::Exception'
>   what():  /home/turbo/opencv-2.4.9/modules/ml/src/svm.cpp:2131: error: (-5) The SVM should be trained first in function CvSVM::predict

How can i solve this? thanks in advance

**Comment by jessica3** [comment]
How to start emotime on windows 7.
In the above described way -
" Untar the downloaded file inside the emotime folder and use the following command to start emotime gui from within the assets folder.
./emotimegui_cli ../resources/haarcascade_frontalface_cbcl1.xml none 48 48 3 5 4 svm ..<give the path of the downloaded classifiers in the last step here>/*.xml  "
 
How to run this command in windows

**Comment by luca-m** [comment]
closing.
