### ISSUE TITLE
Gabor Features Used

### ISSUE THREAD

**Issue by AswinKakarot** [luca-m/emotime#74]
I'm doing my Mini Project on emotion detection. I'm writing the code on Python, They gave me a two month window to report my project. So I don't have enough time to train an svm on my own. That is when I came across your program. I'm using your 1 vs all classifiers for classification. Since I'm unable to run your program. I cant seem to make understand much about the inputs

I'm attaching the result of Gabor transformation below.
These are my parameters for building Gabor Kernel.
        ksize = 7
        LAMBDAS = {"beg": 8, "end": 16}
        THETAS = {"beg": 0, "end": (np.pi)/2}
        gamma = 0.5
        psi = 0
        sigma = 2.2
#Number of lambdas used
        nlambda = 5 
#Number of thetas used
        ntheta = 8 
#kernal Building code
for lambd in np.arange(LAMBDAS['beg'], LAMBDAS['end'], (LAMBDAS['end'] - LAMBDAS['beg']) / float(nlambda)):
            for theta in np.arange(THETAS['beg'], THETAS['end'], (THETAS['end'] - THETAS['beg']) / float(ntheta)):
                kern = cv2.getGaborKernel((ksize, ksize), sigma, theta, lambd, gamma, psi, ktype=cv2.CV_32F)
                kern /= 1.5 * kern.sum()
                filters.append(kern)

I want to know which of these features I can use for prediction from the trained xml files you have provided. Do I need to change the parameters?

![gabor](https://cloud.githubusercontent.com/assets/11333439/13546679/9643cede-e2db-11e5-9b39-d88d813ae024.png)

**Comment by luca-m** [comment]
Hi,

If you want calculate the gabor filter bank in python you could take a look at https://github.com/luca-m/emotime/blob/master/src/gaborbank/GaborBank.h for the parameter of the bank and at https://github.com/luca-m/emotime/blob/master/src/gaborbank/GaborBank.cpp#L171 for the calculation of the bank. 

Hope it helps.
Bests,
-lm

**Comment by harshsavasil** [comment]
@AswinKakarot Hey My mini project is same as yours. Could me guide me how to complete and from where to start.?

**Comment by harshsavasil** [comment]
@AswinKakarot  I haven't started implementation and i have 15 days for completing. I would be very grateful if you could push me in the right direction of learning.

**Comment by AswinKakarot** [comment]
Well. I couldn't finish the project in time. It's a very large project. I only showed partial output. Are you coding in Python?

**Comment by harshsavasil** [comment]
yes I am . Thanks for replying so soon

**Comment by harshsavasil** [comment]
i am coding on python.

**Comment by AswinKakarot** [comment]
Please email me. I could sent you some useful articles.

**Comment by harshsavasil** [comment]
@AswinKakarot  I don't know your email id?

**Comment by AswinKakarot** [comment]
I think its there in my profile.

**Comment by harshsavasil** [comment]
I emailed u @AswinKakarot
