### ISSUE TITLE
emotimegui_cli run but camera shown in black

### ISSUE THREAD

**Issue by cikel87** [luca-m/emotime#75]
First, I would like to thanks to Luca and all the contributors, it seen to be a great job.

I'm using master-emotime with clasifier svm_1vsallext_74_74_1_5_8_7bfc0cda.tar.gz.

Within assets dir, I use:

./emotimegui_cli ../resources/haarcascade_frontalface_cbcl1.xml ../resources/haarcascade_eye.xml 74 74 1 5 8 svm ../svm_1vsallext_74_74_1_5_8_7bfc0cda/*.xml

and this is the result:

![captura de pantalla de 2016-03-21 11 32 25](https://cloud.githubusercontent.com/assets/8290297/13921858/b90e22fa-ef58-11e5-8c4f-8eba8d2a77fc.png)
(camera shown in black)

My webcam works in this linux distribution (Ubuntu 14.04)

Please, could someone explain what I'm doing wrong, really I would appreciate.

Thanks!

**Comment by luca-m** [comment]
I think it cant detect a face
Il 21/mar/2016 15:46, "cikel87" <notifications@github.com> ha scritto:

**Comment by pranav94** [comment]
Had the same issue.

Try using the default frontal face classifier: emotime-master/resources/haarcascade_frontalface_default.xml instead of cbcl1. Worked for me.

Also try using the absolute paths.

**Comment by cikel87** [comment]
Yes, like Luca say, it cant detect a face. I would try frontal face classifier and I would let you know...

**Comment by luca-m** [comment]
closing
