### ISSUE TITLE
Stuck at disgust.

### ISSUE THREAD

**Issue by pranav94** [luca-m/emotime#76]
Brilliant work by Luca and all the contributors.

I'm using emotime-master with clasifier svm_1vsallext_74_74_1_5_8_7.

I've been using the command `echo "VIDEOPATH" | ./emotimegui_cli /emotime-master/resources/haarcascade_frontalface_default.xml none 74 74 1 5 8 svm ..emotime-master/svm_1vsallext_74_74_1_5_8_7bfc0cda/*.xml`

Here is a screenshot of the result.

![emotime _screenshot_23 03 2016](https://cloud.githubusercontent.com/assets/11873683/13986001/fa3f04aa-f125-11e5-831b-bafbcac790e6.png)

The emotion is stuck at disgust with the score of 10.5 and does not change.
If someone could point out what the problem is that would be really helpful.

Thanks!

**Comment by cikel87** [comment]
Yes, I've the same problem.. I'm working on it...
