### ISSUE TITLE
The file uploaded on copy.com is no longer avaliable

### ISSUE THREAD

**Issue by ritou11** [luca-m/emotime#77]
The file uploaded on copy.com is no longer avaliable now. Could you upload it again, please?
>From www.copy.com 
Copy Service is Unavailable.
Service is no longer available as of May 1, 2016.

**Comment by luca-m** [comment]
Re-uploaded: 
* 1vsall https://mega.nz/#!5JJiTLaQ
* 1vsallext https://mega.nz/#!JNgGzarb
